package com.jacky.beedee.support.dao.generate;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jacky.beedee.support.dao.module.Preference;

import com.jacky.beedee.support.dao.generate.PreferenceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig preferenceDaoConfig;

    private final PreferenceDao preferenceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        preferenceDaoConfig = daoConfigMap.get(PreferenceDao.class).clone();
        preferenceDaoConfig.initIdentityScope(type);

        preferenceDao = new PreferenceDao(preferenceDaoConfig, this);

        registerDao(Preference.class, preferenceDao);
    }
    
    public void clear() {
        preferenceDaoConfig.clearIdentityScope();
    }

    public PreferenceDao getPreferenceDao() {
        return preferenceDao;
    }

}
